### ISSUE TITLE
Instructor Feedback - Week 5

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [lucaskostecki/MotorcycleMeetup#2]
Nice job getting the one to many in your indie project. This will serve you well moving forward. You also have a good start on the generic dao. 

- [x] This could probably be named better.. Routes? https://github.com/lucaskostecki/MotorcycleMeetup/blob/fb39fdc7fa233c004ab39c01a7cd2649e849a294/src/test/java/persistence/UserDaoTest.java#L69
- [ ] This might provide you with some inspiration with regard to getting entities by multiple properties: https://github.com/MadJavaEntSpring2019/FatBikeTrailReports/blob/master/src/main/java/com/paulawaite/fbtr/persistence/GenericDao.java
- [ ] I'd strongly recommend a separate test for each entity  => add in a RouteDaoTest to help ensure all aspects of adding, deleting, etc., the Route work. This will be key as you move forward to verify annotations and the db set up are always correct.
- [ ] Consider a test for deleting a user - are routes deleted? Should they be deleted?

**Comment by pawaitemadisoncollege** [comment]
Changed RouteDao to RouteDaoTest above....

**Comment by lucaskostecki** [comment]
I will be rewriting the test cases this week. Thanks.
